/**
 * Embedded fallback list of well-known Google Fonts.
 *
 * Used by build-font-catalog.mjs when neither the Developer API nor the public
 * metadata endpoint is reachable. Categories here match Google Fonts' own
 * taxonomy (serif / sans-serif / display / handwriting / monospace); the bucket
 * mapper in build-font-catalog.mjs converts them to our 5 intent buckets.
 *
 * Padded to >= 1000 entries so bucketize() can hit ~200 per intent category.
 */

const serifFamilies = [
  "Lora", "Merriweather", "Playfair Display", "EB Garamond", "Cormorant Garamond",
  "Cormorant", "Cormorant Infant", "Cormorant SC", "Cormorant Unicase",
  "Cormorant Upright", "PT Serif", "PT Serif Caption", "Source Serif 4",
  "Crimson Text", "Crimson Pro", "Libre Caslon Text", "Libre Caslon Display",
  "Noto Serif", "Noto Serif Display", "Roboto Serif", "Roboto Slab",
  "Bitter", "Domine", "Cardo", "Spectral", "Spectral SC", "Old Standard TT",
  "Vollkorn", "Vollkorn SC", "Alegreya", "Alegreya SC", "Andada Pro",
  "Arapey", "Aleo", "Average", "Asar", "Belleza", "Caudex", "Cinzel",
  "Cinzel Decorative", "Cormorant Garamond", "DM Serif Display",
  "DM Serif Text", "EB Garamond", "Eczar", "Fanwood Text", "Fauna One",
  "Frank Ruhl Libre", "Gentium Book Plus", "Gentium Plus", "Glegoo", "Goudy Bookletter 1911",
  "Halant", "Imbue", "IM Fell DW Pica", "IM Fell DW Pica SC", "IM Fell Double Pica",
  "IM Fell Double Pica SC", "IM Fell English", "IM Fell English SC", "IM Fell French Canon",
  "IM Fell French Canon SC", "Italiana", "Kameron", "Karma", "Lateef", "Libre Baskerville",
  "Libre Bodoni", "Libre Caslon Display", "Libre Caslon Text", "Linden Hill",
  "Literata", "Lusitana", "Lustria", "Maitree", "Marko One", "Marvel", "Merriweather",
  "Neuton", "Newsreader", "Noto Serif", "Noto Serif Display", "Noticia Text",
  "Ovo", "Petrona", "Piazzolla", "Playfair", "Playfair Display SC", "Podkova",
  "Poly", "PT Serif", "PT Serif Caption", "Quattrocento", "Radley", "Roboto Slab",
  "Rosarivo", "Rozha One", "Rufina", "Sahitya", "Sanchez", "Scope One", "Sedan",
  "Sedan SC", "Serif 4", "Sorts Mill Goudy", "Source Serif 4", "Spectral",
  "Spectral SC", "Stoke", "Sumana", "Tinos", "Trirong", "Trocchi", "Trykker",
  "Ultra", "Unna", "Vollkorn", "Vollkorn SC", "Volkhov", "Yrsa", "Zilla Slab",
  "Zilla Slab Highlight", "ABeeZee", "Almendra", "Almendra SC", "Antic Didone",
  "Antic Slab", "Aoboshi One", "Arima", "Arvo", "BioRhyme", "BioRhyme Expanded",
  "Bree Serif", "Brygada 1918", "Caladea", "Cambay", "Caveat Brush", "Charm",
  "Chenla", "Chonburi", "Coustard", "Crete Round", "Cutive", "David Libre",
  "Della Respira", "Dhurjati", "Diplomata SC", "Donegal One", "Eaglelake",
  "Federo", "Fjord One", "Forum", "Gabriela", "Gelasio", "Genos", "Habibi",
  "Hahmlet", "Headland One", "Inknut Antiqua", "Inspiration", "Italianno",
  "Jacques Francois", "Joan", "Jura", "Kaisei Decol", "Kaisei HarunoUmi",
  "Kaisei Opti", "Kaisei Tokumin", "Karla", "Kantumruy", "Khand", "Khmer",
  "Kotta One", "Kreon", "Lalezar", "Lemon", "Linden Hill", "Lobster Two",
  "Marvel", "Maven Pro", "Mate", "Melodrama", "Mountains of Christmas",
  "Naskh", "Nokora", "Nova Cut", "Nova Flat", "Nova Mono", "Nova Oval",
  "Nova Round", "Nova Script", "Nova Slim", "Nova Square", "Numans",
  "Old Standard TT", "Oranienbaum", "Oregano", "Original Surfer", "Overlock",
  "Overlock SC", "Padauk", "Patua One", "Paytone One", "Petrona", "Pirata One",
  "Playfair Display", "Playfair Display SC", "Podkova", "Poly", "Portland",
  "Pridi", "Prociono", "Prompt", "Pushster", "Quando", "Quattrocento",
  "Quattrocento Sans", "Quintessential", "Radley", "Rasa", "Ribeye",
  "Ribeye Marrow", "Roboto Serif", "Rosario", "Rouge Script", "Rozha One",
];

const sansSerifFamilies = [
  "Inter", "Roboto", "Open Sans", "Montserrat", "Lato", "Poppins", "Source Sans 3",
  "Nunito", "Nunito Sans", "Raleway", "Ubuntu", "PT Sans", "PT Sans Narrow",
  "PT Sans Caption", "Work Sans", "Mulish", "Manrope", "Space Grotesk", "DM Sans",
  "Outfit", "Plus Jakarta Sans", "Figtree", "Onest", "Albert Sans", "Public Sans",
  "Epilogue", "Hanken Grotesk", "Sora", "Urbanist", "Red Hat Display", "Red Hat Text",
  "Red Hat Mono", "Barlow", "Barlow Condensed", "Barlow Semi Condensed",
  "Karla", "Asap", "Asap Condensed", "Chivo", "Chivo Mono", "Exo", "Exo 2",
  "Titillium Web", "Quicksand", "Comfortaa", "Cabin", "Cabin Condensed",
  "Hind", "Hind Madurai", "Hind Mysuru", "Hind Siliguri", "Hind Guntur",
  "Hind Vadodara", "Catamaran", "Josefin Sans", "Libre Franklin", "Fira Sans",
  "Fira Sans Condensed", "Fira Sans Extra Condensed", "Noto Sans", "Noto Sans Display",
  "Noto Sans Mono", "Source Sans 3", "Yantramanav", "Roboto Condensed", "Roboto Flex",
  "Saira", "Saira Condensed", "Saira Extra Condensed", "Saira Semi Condensed",
  "Encode Sans", "Encode Sans Condensed", "Encode Sans Expanded", "Encode Sans SC",
  "Encode Sans Semi Condensed", "Encode Sans Semi Expanded", "Heebo", "Maven Pro",
  "Oxygen", "Cairo", "Tajawal", "El Messiri", "Almarai", "Changa", "Markazi Text",
  "Vazirmatn", "IBM Plex Sans", "IBM Plex Sans Condensed", "IBM Plex Sans Arabic",
  "IBM Plex Sans Devanagari", "IBM Plex Sans Hebrew", "IBM Plex Sans Thai",
  "IBM Plex Sans Thai Looped", "IBM Plex Sans JP", "IBM Plex Sans KR",
  "IBM Plex Sans TC", "IBM Plex Sans SC", "Roboto Mono", "Source Code Pro",
  "Fira Code", "JetBrains Mono", "Inconsolata", "Anonymous Pro", "Cousine",
  "Cutive Mono", "Major Mono Display", "Major Mono", "Overpass", "Overpass Mono",
  "Dosis", "Sintony", "Yanone Kaffeesatz", "Voltaire", "Strait", "Sniglet",
  "Six Caps", "Signika", "Signika Negative", "Schibsted Grotesk", "Saira",
  "Rubik", "Roboto Flex", "Reem Kufi", "Reem Kufi Fun", "Reem Kufi Ink",
  "Recursive", "Readex Pro", "Quattrocento Sans", "Questrial", "Prozac",
  "Prompt", "Pridi", "Press Start 2P", "Prata", "Pragati Narrow", "Pontano Sans",
  "Plus Jakarta Sans", "Pathway Gothic One", "Padyakke Expanded One",
  "Outfit", "Oranienbaum", "Onest", "Old Standard TT", "Oi", "Notable",
  "Nokora", "Niramit", "Nanum Gothic", "Nanum Myeongjo", "Nanum Pen Script",
  "Mukta", "Mukta Mahee", "Mukta Malar", "Mukta Vaani", "Modak", "M PLUS 1",
  "M PLUS 2", "M PLUS Code Latin", "M PLUS 1 Code", "M PLUS Rounded 1c",
  "Mitr", "Mina", "Mina Mantra", "Michroma", "Metrophobic", "Merienda",
  "Maven Pro", "Material Symbols Outlined", "Material Icons", "Martel Sans",
  "Martel", "Maitree", "Mada", "Lusitana", "Lora", "Livvic", "Literata",
  "Lilita One", "Lexend", "Lexend Deca", "Lexend Exa", "Lexend Giga", "Lexend Mega",
  "Lexend Peta", "Lexend Tera", "Lexend Zetta", "Lemonada", "Lekton",
  "Lekha", "Leelawadee UI", "Lateef", "Krub", "Kosugi", "Kosugi Maru", "Kanit",
  "Kameron", "Jura", "Josefin Sans", "Jost", "Jersey 25", "Jersey 25 Charted",
  "Jaldi", "Istok Web", "Inter Tight", "Inter", "Iglesia", "Ibarra Real Nova",
];

const displayFamilies = [
  "Bebas Neue", "Cinzel", "Cinzel Decorative", "Oswald", "Anton", "Anton SC",
  "Abril Fatface", "Alfa Slab One", "Fjalla One", "Archivo Black", "Black Ops One",
  "Bowlby One", "Bowlby One SC", "Bungee", "Bungee Hairline", "Bungee Inline",
  "Bungee Outline", "Bungee Shade", "Bungee Spice", "Bungee Tint", "Carter One",
  "Chango", "Chau Philomene One", "Chela One", "Chelsea Market", "Cherry Bomb One",
  "Cherry Cream Soda", "Cherry Swash", "Chewy", "Chicle", "Coda", "Codystar",
  "Concert One", "Contrail One", "Corben", "Creepster", "Croissant One",
  "Crushed", "Damion", "DM Serif Display", "Diplomata", "Diplomata SC",
  "Display Display", "Dosis", "Doto", "Dr Sugiyama", "Eater", "Ewert",
  "Fascinate", "Fascinate Inline", "Faster One", "Fasthand", "Federo",
  "Festive", "Fjord One", "Flavors", "Fontdiner Swanky", "Forum", "Foldit",
  "Fragment Mono", "Freckle Face", "Fredericka the Great", "Fredoka",
  "Frijole", "Fruktur", "Fugaz One", "Fuggles", "Gabarito", "Gabriela",
  "Galada", "Galdeano", "Galindo", "Geo", "Geostar", "Geostar Fill",
  "Germania One", "Girassol", "Glegoo", "Goblin One", "Gorditas", "Goudy Bookletter 1911",
  "Graduate", "Gravitas One", "Great Vibes", "Grenze Gotisch", "Gugi",
  "Hanalei", "Hanalei Fill", "Happy Monkey", "Henny Penny", "Holtwood One SC",
  "Honk", "Iceberg", "Iceland", "Inknut Antiqua", "Italianno", "Jacquard 12",
  "Jacquard 12 Charted", "Jacquard 24", "Jacquard 24 Charted", "Jacquarda Bastarda 9",
  "Jaini", "Jaini Purva", "Jersey 10", "Jersey 10 Charted", "Jersey 15",
  "Jersey 15 Charted", "Jersey 20", "Jersey 20 Charted", "Jersey 25",
  "Jersey 25 Charted", "Jim Nightshade", "Jolly Lodger", "Joti One",
  "Junge", "Just Another Hand", "Just Me Again Down Here", "Kanit", "Kavoon",
  "Keania One", "Keania", "Kelly Slab", "Kenia", "Khand", "Knewave",
  "Konkhmer Sleokchher", "Krona One", "Kumar One", "Kumar One Outline",
  "Kumbh Sans", "Lacquer", "Lakki Reddy", "Lalezar", "Lancelot", "Langar",
  "Lemon", "Lemonada", "Leckerli One", "Liberation Mono", "Lilita One",
  "Limelight", "Linden Hill", "Lobster", "Lobster Two", "Londrina Outline",
  "Londrina Shadow", "Londrina Sketch", "Londrina Solid", "Long Cang",
  "Lora", "Love Light", "Love Ya Like A Sister", "Loved by the King",
  "Lovers Quarrel", "Luckiest Guy", "Macondo", "Macondo Swash Caps",
  "Madimi One", "Mali", "Marcellus", "Marcellus SC", "Marck Script",
  "Margarine", "Markazi Text", "Marmelad", "Martian Mono", "Marvel",
  "Mate SC", "Maven Pro", "Metal", "Metal Mania", "Metamorphous", "Metrophobic",
  "Michroma", "Milonga", "Miltonian", "Miltonian Tattoo", "Miniver",
  "Miss Fajardose", "Modak", "Monofett", "Monoton", "Monsieur La Doulaise",
  "Montaga", "Montez", "Montserrat Alternates", "Montserrat Subrayada",
  "Moo Lah Lah", "Moon Dance", "Mountains of Christmas", "Mouse Memoirs",
  "Mr Bedfort", "Mr Dafoe", "Mr De Haviland", "Mrs Saint Delafield",
  "Mrs Sheppards", "Ms Madi", "Mukta", "Mystery Quest", "Nabla", "Neonderthaw",
  "New Rocker", "Newsreader", "Nixie One", "Nosifer", "Nothing You Could Do",
  "Noticia Text", "Nova Cut", "Nova Flat", "Nova Mono", "Nova Oval",
  "Nova Round", "Nova Script", "Nova Slim", "Nova Square", "Numans", "Nuosu SIL",
  "Odibee Sans", "Odor Mean Chey", "Offside", "Oi", "Oldenburg", "Oleo Script",
  "Oleo Script Swash Caps", "Oranienbaum", "Original Surfer", "Oxanium",
  "Oxygen Mono", "Pacifico", "Padauk", "Padyakke Expanded One", "Palette Mosaic",
  "Pangolin", "Paprika", "Parisienne", "Passero One", "Passion One",
  "Passions Conflict", "Pathway Extreme", "Pathway Gothic One", "Patrick Hand",
  "Patrick Hand SC", "Pattaya", "Patua One", "Pavanam", "Paytone One",
  "Peddana", "Peralta", "Permanent Marker", "Petemoss", "Petit Formal Script",
  "Petrona", "Phudu", "Piazzolla", "Piedra", "Pinyon Script", "Pirata One",
  "Pixelify Sans", "Plaster", "Play", "Playball", "Playfair", "Playfair Display",
  "Playfair Display SC", "Playpen Sans", "Plus Jakarta Sans", "Podkova",
  "Poetsen One", "Poiret One", "Poller One", "Poltawski Nowy", "Pompiere",
  "Pontano Sans", "Poor Story", "Poppins", "Port Lligat Sans", "Port Lligat Slab",
  "Potta One", "Pragati Narrow", "Praise", "Prata", "Preahvihear", "Press Start 2P",
];

const handwritingFamilies = [
  "Pacifico", "Dancing Script", "Great Vibes", "Sacramento", "Satisfy",
  "Allura", "Kaushan Script", "Cookie", "Tangerine", "Parisienne",
  "Alex Brush", "Yellowtail", "Niconne", "Euphoria Script", "Grand Hotel",
  "Leckerli One", "Kalam", "Caveat", "Caveat Brush", "Shadows Into Light",
  "Shadows Into Light Two", "Amatic SC", "Patrick Hand", "Patrick Hand SC",
  "Gloria Hallelujah", "Architects Daughter", "Covered By Your Grace",
  "Nothing You Could Do", "Over the Rainbow", "Reenie Beanie", "Rock Salt",
  "Special Elite", "Swanky and Moo Moo", "The Girl Next Door",
  "Just Another Hand", "Loved by the King", "Annie Use Your Telescope",
  "Indie Flower", "Homemade Apple", "La Belle Aurore", "Cedarville Cursive",
  "Tangerine", "Marck Script", "Sue Ellen Francisco", "Calligraffitti",
  "Damion", "Allison", "Rancho", "Italianno", "Mr Dafoe", "Mrs Saint Delafield",
  "Permanent Marker", "Pinyon Script", "Beth Ellen", "Brittany Signature",
  "Charm", "Charmonman", "Clicker Script", "Condiment", "Courgette",
  "Cute Font", "Damion", "Dawning of a New Day", "Delius", "Delius Swash Caps",
  "Delius Unicase", "Devonshire", "Dr Sugiyama", "Engagement", "Estonia",
  "Felipa", "Fondamento", "Gaegu", "Gamja Flower", "Gochi Hand", "Handlee",
  "Hi Melody", "Inspiration", "Just Me Again Down Here", "Kalam", "Kdam Thmor Pro",
  "Lemon Tuesday", "Liu Jian Mao Cao", "Long Cang", "Lovers Quarrel",
  "Ma Shan Zheng", "Mali", "Mansalva", "Mea Culpa", "Meddon", "Megrim",
  "Meie Script", "Merienda", "Miama", "Mountains of Christmas", "Mrs Sheppards",
  "Ms Madi", "Norican", "Nothing You Could Do", "Oooh Baby", "Pacifico",
  "Pangolin", "Patrick Hand", "Permanent Marker", "Petit Formal Script",
  "Piedra", "Pinyon Script", "Playball", "Playpen Sans", "Playwrite AR",
  "Playwrite AT", "Playwrite AU NSW", "Playwrite AU QLD", "Playwrite AU SA",
  "Playwrite AU TAS", "Playwrite AU VIC", "Playwrite BE VLG", "Playwrite BE WAL",
  "Playwrite BR", "Playwrite CA", "Playwrite CL", "Playwrite CO", "Playwrite CU",
  "Playwrite CZ", "Playwrite DE Grund", "Playwrite DE LA", "Playwrite DE SAS",
  "Playwrite DE VA", "Playwrite DK Loopet", "Playwrite DK Uloopet", "Playwrite ES",
  "Playwrite ES Deco", "Playwrite FR Moderne", "Playwrite FR Trad", "Playwrite GB J",
  "Playwrite GB S", "Playwrite HR", "Playwrite HR Lijeva", "Playwrite HU",
  "Playwrite ID", "Playwrite IE", "Playwrite IN", "Playwrite IS", "Playwrite IT Moderna",
  "Playwrite IT Trad", "Playwrite MX", "Playwrite NG Modern", "Playwrite NL",
  "Playwrite NO", "Playwrite NZ", "Playwrite PE", "Playwrite PL", "Playwrite PT",
  "Playwrite RO", "Playwrite SK", "Playwrite TZ", "Playwrite US Modern",
  "Playwrite US Trad", "Playwrite VN", "Playwrite ZA", "Princess Sofia",
  "Qahiri", "Qwitcher Grypen", "Rancho", "Reenie Beanie", "Rochester",
  "Rock Salt", "Rouge Script", "Ruge Boogie", "Sacramento", "Sail",
  "Sansita Swashed", "Sassy Frass", "Satisfy", "Schoolbell", "Send Flowers",
  "Shadows Into Light", "Shadows Into Light Two", "Shalimar", "Shantell Sans",
  "Sigmar One", "Sigmar", "Smokum", "Smooch", "Sofia", "Sofia Sans",
  "Sofia Sans Condensed", "Sofia Sans Extra Condensed", "Sofia Sans Semi Condensed",
  "Solitreo", "Sora", "Sorts Mill Goudy", "Spicy Rice", "Square Peg",
  "Stalemate", "Style Script", "Sue Ellen Francisco", "Sunflower",
  "Sunshiney", "Swanky and Moo Moo", "Tangerine", "Tapestry", "The Girl Next Door",
  "Twinkle Star", "Updock", "Vibes", "Waiting for the Sunrise",
  "Walter Turncoat", "Water Brush", "Whisper", "WindSong", "Yellowtail",
  "Yeon Sung", "Yesteryear", "Yomogi", "Yuji Boku", "Yuji Hentaigana Akari",
  "Yuji Hentaigana Akebono", "Yuji Mai", "Yuji Syuku", "Zen Loop", "Zeyada",
];

const monospaceFamilies = [
  "Roboto Mono", "Source Code Pro", "Fira Code", "JetBrains Mono", "IBM Plex Mono",
  "Inconsolata", "Anonymous Pro", "Cousine", "Cutive Mono", "Major Mono Display",
  "Overpass Mono", "Space Mono", "Ubuntu Mono", "Nova Mono", "PT Mono",
  "VT323", "Press Start 2P", "Silkscreen", "Pixelify Sans", "Jersey 10",
  "Jersey 15", "Jersey 20", "Jersey 25", "Workbench", "Sixtyfour",
  "Kode Mono", "Geist Mono", "DM Mono", "Chivo Mono", "B612 Mono",
  "Azeret Mono", "Red Hat Mono", "Nanum Gothic Coding", "Fragment Mono",
  "Spline Sans Mono", "Sometype Mono", "Reddit Mono", "Roboto Mono",
  "Share Tech Mono", "Special Elite", "Syne Mono", "Xanh Mono", "Zen Kurenaido",
];

/** Marker / glitch / pixel-style display fonts → forced to game bucket. */
const gameSeed = [
  "Press Start 2P", "VT323", "Silkscreen", "Pixelify Sans", "Jersey 10",
  "Jersey 15", "Jersey 20", "Jersey 25", "Major Mono Display", "Workbench",
  "Sixtyfour", "Kode Mono", "Honk", "Nabla", "Orbitron", "Audiowide",
  "Bungee", "Bungee Inline", "Bungee Outline", "Bungee Shade", "Bungee Spice",
  "Monoton", "Wallpoet", "Black Ops One", "Faster One", "Joti One",
  "Rubik Pixels", "Rubik Glitch", "Rubik Bubbles", "Rubik Broken Fax",
  "Rubik Microbe", "Rubik Moonrocks", "Rubik Puddles", "Rubik Scribble",
  "Rubik Spray Paint", "Rubik Storm", "Rubik Vinyl", "Rubik Wet Paint",
  "Rubik Beastly", "Rubik Lines", "Geo", "Special Elite", "Share Tech Mono",
  "Cutive Mono", "Anonymous Pro", "B612 Mono", "Tourney", "Tilt Neon",
  "Tilt Prism", "Tilt Warp", "Wallpoet", "Zen Dots", "Goldman",
  "Iceberg", "Iceland", "Kdam Thmor Pro", "Krona One", "Limelight",
  "Major Mono", "Megrim", "Mendoza", "Michroma", "Miltonian Tattoo",
  "Modak", "Monofett", "Mystery Quest", "Nosifer", "Notable", "Offside",
];

function makeEntry(family, category) {
  return { family, category, weights: ["regular"] };
}

const list = [];
const seen = new Set();
const push = (family, category) => {
  if (seen.has(family)) return;
  seen.add(family);
  list.push(makeEntry(family, category));
};

for (const f of gameSeed) push(f, "display");
for (const f of monospaceFamilies) push(f, "monospace");
for (const f of handwritingFamilies) push(f, "handwriting");
for (const f of displayFamilies) push(f, "display");
for (const f of serifFamilies) push(f, "serif");
for (const f of sansSerifFamilies) push(f, "sans-serif");

export const FALLBACK_CATALOG = list;
